import { AssessmentFormat, DocumentStage, ToolkitData, formatLabels } from './types';

type ExampleBank = Partial<Record<keyof ToolkitData, string[]>>;
const commonBefore: ExampleBank = {
  expectations: ['A strong response identifies the relevant economic mechanism, applies it to the question, and explains why the evidence supports the conclusion rather than merely naming a theory.', 'Good performance combines accurate analysis with explicit assumptions, proportionate evidence and a clear line of reasoning.'],
  criteria: ['Markers will consider accuracy, analytical reasoning, appropriate use of evidence, application to the task and clarity of communication. A technically correct answer may still be limited if its assumptions or implications are not explained.'],
  preparation: ['Practise selecting an approach before looking at a solution, complete representative questions under realistic conditions, and compare your reasoning with the rubric or model approach.'],
  workedExamples: ['Learning outcome: Apply an appropriate economic model to an unfamiliar policy problem and reach a justified conclusion. Practice task: A city is considering a binding rent ceiling. Explain the likely short-run effects and one important limitation of the model. A developing response says only that “rent falls and demand rises”. This identifies directions of change but does not explain the mechanism, distinguish demand from quantity demanded, or address supply. A stronger response identifies the ceiling relative to equilibrium, traces the shortage through quantity demanded and quantity supplied, and uses a labelled diagram. A high-quality response then states the competitive-market assumptions, distinguishes short- from longer-run responses, and explains why allocation and quality effects matter for the policy conclusion. Student self-check: Have I selected the model, traced the mechanism, interpreted the result in context, stated the assumptions and reached a conclusion proportionate to the evidence?'],
  commonPitfalls: ['Common pitfalls include answering a nearby question, reproducing material without applying it, leaving assumptions implicit, reporting output without interpretation, and allocating time or words unevenly.'],
  feedbackAvailable: ['Students will receive individual comments and/or rubric indicators, supported by a cohort-level summary explaining recurring strengths, misconceptions and practical next steps.'],
  usingFeedback: ['Translate each feedback point into one action: what to continue, what to change, and where to practise it. Revisit this plan before the next related assessment.'],
};
const commonAfter: ExampleBank = {
  cohortContext: ['This document summarises non-identifiable themes across the cohort. It complements individual feedback and does not replace comments on your own work.'],
  performancePatterns: ['Responses were generally strongest when students stated the economic mechanism before applying evidence. Do not add percentages or averages unless they have been checked and supplied by the module team.'],
  cohortStrengths: ['Many students selected relevant concepts and structured their responses clearly. Stronger work made the link between evidence and conclusion explicit.'],
  improvementAreas: ['The main opportunity is to move from description to analysis: explain the causal or strategic mechanism, state assumptions and consider the limits of the conclusion.'],
  criteriaApplication: ['Higher-performing work combined accuracy with application and judgement. The rubric was applied holistically: listing more material did not compensate for weak relevance or unexplained reasoning.'],
  improvedApproaches: ['Learning outcome: Interpret empirical results and reach a conclusion that is proportionate to the research design. Illustrative task: Explain what an estimated coefficient of −0.08 means when the dependent variable is log sales and the explanatory variable is a one-unit policy indicator. A limited response says, “The policy reduces sales by 8% and the effect is significant.” This is too confident because it does not identify the comparison, uncertainty or assumptions. An improved response says, “Conditional on the controls in this specification, treated observations are associated with approximately 8% lower sales than the comparison group; the confidence interval should be reported to show precision. A causal interpretation additionally requires the identification assumptions to be credible.” This is stronger because it interprets magnitude, distinguishes association from causation and makes uncertainty visible. Next-step self-check: meaning, magnitude, precision, assumptions, limits and decision relevance.'],
  futureUse: ['Carry this feedback into later modules by using a short pre-submission check: question answered, method justified, assumptions visible, evidence interpreted and conclusion proportionate.'],
  debriefSupport: ['Bring one paragraph, calculation or feedback point to the debrief and identify the decision you would make differently next time.'],
};
const formatBefore: Record<AssessmentFormat, ExampleBank> = {
  in_person_exam: { assessmentPurpose: ['An in-person examination is appropriate because it asks students to apply core concepts independently under time constraints, demonstrate fluency in economic or quantitative reasoning, and select and justify a method in comparable conditions. Foundational fluency also helps graduates evaluate rather than simply accept AI-generated analysis.'], preparation: ['Use timed, closed-resource practice after untimed learning. Practise identifying the method, showing essential workings and explaining the economic meaning of the result.'], assessmentRequirements: ['Answer the specified number of questions. State essential assumptions, show material workings, label diagrams and follow the published rules on permitted materials.'] },
  open_book_exam: { assessmentPurpose: ['A time-limited open-book examination assesses selection, application and judgement rather than recall alone. Access to resources makes it especially important to decide what is relevant and construct a defensible answer efficiently.'], preparation: ['Organise resources by decision or concept, not by week. Practise locating evidence quickly and answering unfamiliar questions without copying notes into the response.'] },
  essay_report: { assessmentPurpose: ['The essay or report assesses the ability to frame a focused question, integrate theory and evidence, evaluate competing explanations and communicate a reasoned conclusion for an academic or professional reader.'], expectations: ['Strong work has a clear analytical spine: each section advances the answer, evidence is evaluated rather than accumulated, and the conclusion follows from the argument.'] },
  quant_problem_set: { assessmentPurpose: ['The problem set develops quantitative fluency by requiring students to choose and execute an appropriate method, show reasoning, interpret results and diagnose whether an answer is economically plausible.'], commonPitfalls: ['Avoid presenting calculations without interpretation, rounding too early, omitting units, using a method without checking its conditions, or treating software output as self-explanatory.'] },
  econometrics_project: { assessmentPurpose: ['The data project assesses the full empirical reasoning chain: a motivated question, appropriate data and specification, reproducible analysis, interpretation, diagnostic judgement and honest discussion of limitations.'], expectations: ['Good performance explains why the design can answer the question, documents data decisions, interprets magnitude and uncertainty, and distinguishes association from causal evidence.'] },
  case_analysis: { assessmentPurpose: ['Case analysis assesses whether students can diagnose an ambiguous organisational or market problem, prioritise evidence, apply relevant frameworks selectively and recommend an implementable course of action.'], expectations: ['Strong work makes trade-offs explicit and explains why the recommended action is preferable under the case constraints.'] },
  presentation: { assessmentPurpose: ['The presentation assesses disciplined selection, audience-aware communication, evidence-based judgement and the ability to explain or defend analysis within a limited time.'], preparation: ['Rehearse aloud to time, test the narrative without slides, and prepare concise answers to likely questions about assumptions, evidence and recommendations.'] },
  group_project: { assessmentPurpose: ['The group project combines subject knowledge with coordination, integration of different contributions and collective responsibility for a coherent analytical output—capabilities used in professional economics and management work.'], commonPitfalls: ['Avoid dividing the task into disconnected pieces, leaving integration until the end, or allowing presentation consistency to substitute for analytical coherence.'] },
  take_home: { assessmentPurpose: ['A take-home task allows sustained analysis of a more complex problem. It assesses judgement in selecting methods and evidence, transparent use of permitted tools, and the ability to refine a coherent response within the stated rules.'], assessmentRequirements: ['Follow the module’s rules on collaboration, sources and AI tools. Where AI use is permitted, verify outputs, disclose use as required and remain responsible for every claim, calculation and citation.'] },
};

export function examplesFor(stage: DocumentStage, format: AssessmentFormat | ''): ExampleBank {
  const base = stage === 'before' ? commonBefore : commonAfter;
  if (stage === 'after' || !format) return base;
  const merged: ExampleBank = { ...base };
  for (const [key, values] of Object.entries(formatBefore[format])) merged[key as keyof ToolkitData] = [...(base[key as keyof ToolkitData] || []), ...(values || [])];
  return merged;
}

export function aiPrompt(stage: DocumentStage, format: AssessmentFormat | '', product: 'guide' | 'slides' = 'guide') {
  const formatText = format ? formatLabels[format] : 'the assessment format supported by the source material';
  const shared = `You are helping a university module leader create an editable student-facing document for an undergraduate economics or management module. Before drafting, ask the user to upload or paste approved source documents wherever possible: the module specification, syllabus, module handbook, assessment brief, assessment rubric, learning outcomes and any other approved module documentation. Explain that fuller source material improves accuracy and reduces manual editing.

Use supplied sources for all module-specific facts. Extract learning outcomes only when they appear in the supplied material and reproduce their meaning accurately. Never invent learning outcomes, assessment requirements, module content, dates, rules, links, grade boundaries, marking-band labels, statistics or cohort results. Leave unsupported module-specific values empty and list every material gap in missingInformation. You may offer a general pedagogical suggestion only for a missing explanatory field such as assessment rationale, preparation, feedback use or employability. Prefix it with "[AI suggestion - verify]" and ask the module leader to confirm, edit or replace it. Never present a suggestion as an approved module fact.

Use concise, constructive language and a feedback-for-learning approach: help students recognise quality, diagnose their next step and transfer learning to future work. Do not include student names, IDs, individual scripts, raw marks, named comments or identifiable student information.

For every worked example or improved approach, explicitly identify the exact supplied learning outcome or outcomes being demonstrated. If no relevant learning outcome is supplied, leave the example empty and record this in missingInformation; do not invent one. Build a concrete, discipline-relevant but assessment-safe example rather than generic advice. Use this structure: (1) learning outcome; (2) illustrative task or question; (3) a short developing excerpt or approach; (4) a precise diagnosis against the supplied criterion and learning outcome; (5) a materially improved excerpt or approach that demonstrates the reasoning, not merely a description of it; (6) why the revision is stronger; and (7) a transferable student self-check or next practice step. Where useful, show intermediate reasoning, a diagram plan, calculation interpretation, evidence choice or decision logic. Aim for enough substance to teach from—normally 180–300 words for a narrative worked example—while keeping any slide summary concise.

Use the supplied marking guide and rubric to distinguish quality. Use exact band labels only when the supplied rubric provides them; otherwise use neutral descriptors without implying an official grade. Make differences diagnostic rather than cosmetic: show how selection, application, evidence, assumptions, interpretation and judgement change the quality of the response. Use a generic, staff-created or properly anonymised example. Do not reproduce a secure live assessment question or provide a complete solution to a current assessment unless the source explicitly confirms it is approved for student release. Do not present AI-generated text as an official model answer.

Return ONLY one valid JSON object with string values and no markdown.`;
  if (stage === 'before' && product === 'slides') return `${shared}\n\nCreate content for a three-slide Assessment and Feedback Slides pilot for ${formatText}, plus an accessible narrative companion document. Preserve this order: (1) assessment components and rationale alongside plain-English learning outcomes; (2) marking criteria and fairness/clarity safeguards alongside feedback opportunities and how students can use feedback; (3) two to four relevant skills and employability benefits, each linked to a concrete assessment activity. Also provide preparation, common pitfalls, worked examples and support routes for the companion document. Use exactly these keys:\n${JSON.stringify({ moduleCode:'', moduleTitle:'', level:'', faculty:'', department:'', moduleLeader:'', academicYear:'', teachingPeriod:'', assessmentProfile:'', assessmentFormat:format, assessmentStructure:'', assessmentPurpose:'', learningOutcomes:'', criteria:'', fairnessAndClarity:'', preparation:'', workedExamples:'', commonPitfalls:'', assessmentRequirements:'', feedbackAvailable:'', usingFeedback:'', supportRoutes:'', skillsEmployability:'', keatsLocation:'', missingInformation:'' }, null, 2)}\n\nUse assessmentProfile values exam, mixed or coursework. Keep slide-ready fields concise. In learningOutcomes, use only supplied outcomes and translate them into plain English without adding new outcomes. Explain alignment only where the supplied outcomes and assessment evidence support it. In skillsEmployability, connect each claimed skill to what students actually do in this assessment. Make clear that all [AI suggestion - verify] text requires academic confirmation.`;
  if (stage === 'before') return `${shared}\n\nCreate an Assessment and Feedback Guide for ${formatText}. In learningOutcomes, reproduce or faithfully translate only the relevant outcomes supplied in approved module documents. Make workedExamples a substantive teaching resource that visibly demonstrates those outcomes and shows why the supplied criteria distinguish quality. Use exactly these keys:\n${JSON.stringify({ moduleCode:'', moduleTitle:'', level:'', faculty:'', department:'', moduleLeader:'', academicYear:'', teachingPeriod:'', assessmentProfile:'', assessmentFormat:format, assessmentStructure:'', assessmentPurpose:'', learningOutcomes:'', expectations:'', criteria:'', preparation:'', workedExamples:'', commonPitfalls:'', assessmentRequirements:'', feedbackAvailable:'', usingFeedback:'', supportRoutes:'', keatsLocation:'', missingInformation:'' }, null, 2)}\n\nUse assessmentProfile values exam, mixed or coursework. Explain the educational purpose without claiming the format is inherently superior or valuable merely because it restricts AI. Leave unsupported module facts empty and record gaps in missingInformation.`;
  return `${shared}\n\nCreate a cohort-level General Feedback document for ${formatText}. In addition to the approved syllabus, learning outcomes, marking guide and rubric, use only checked, anonymised aggregate cohort themes. Never infer or calculate performance statistics; include a numeric pattern only when explicitly supplied and checked. In learningOutcomes, reproduce or faithfully translate only the relevant approved outcomes. Make improvedApproaches a substantive teaching resource linked explicitly to those outcomes, and explain how the supplied criteria distinguished performance in criteriaApplication. Use exactly these keys:\n${JSON.stringify({ moduleCode:'', moduleTitle:'', level:'', faculty:'', department:'', moduleLeader:'', academicYear:'', teachingPeriod:'', assessmentProfile:'', assessmentFormat:format, cohortContext:'', learningOutcomes:'', evaluatedLearning:'', performancePatterns:'', cohortStrengths:'', improvementAreas:'', criteriaApplication:'', improvedApproaches:'', futureUse:'', debriefSupport:'', keatsLocation:'', missingInformation:'' }, null, 2)}\n\nUse assessmentProfile values exam, mixed or coursework. Make clear that cohort feedback complements rather than replaces individual feedback. Leave unsupported module or cohort facts empty and record gaps in missingInformation.`;
}

const beforeAiSample = {
  moduleCode: 'DEMO2001',
  moduleTitle: 'Applied Microeconomics (fictional example)',
  level: 'Level 5',
  faculty: 'Example Business School',
  department: 'Economics',
  moduleLeader: 'Dr Alex Morgan',
  academicYear: '2026/27',
  teachingPeriod: 'Term 1',
  assessmentProfile: 'exam',
  assessmentFormat: 'in_person_exam',
  assessmentStructure: 'Fictional example: a two-hour, closed-book examination made up of analytical, quantitative and applied questions. The final document should replace this text with the approved structure and weighting.',
  assessmentPurpose: 'The examination assesses whether students can select and apply relevant microeconomic concepts independently, show essential analytical or quantitative reasoning and explain the economic meaning of their conclusions. It tests fluent application and judgement rather than recall alone.',
  learningOutcomes: 'LO1: Explain how incentives and constraints shape market behaviour. LO2: Apply an appropriate microeconomic model to an unfamiliar policy problem. LO3: Interpret analytical or quantitative results and reach a justified conclusion.',
  expectations: 'Students should identify the relevant economic mechanism, state necessary assumptions, use diagrams or calculations accurately, interpret the result in context and reach a conclusion supported by their analysis.',
  criteria: 'The fictional rubric considers accuracy, relevance, analytical method, application, interpretation and clarity. Developing work identifies a relevant idea but applies it incompletely. Secure work applies an appropriate model accurately and explains the main result. Strong work integrates method, economic intuition, assumptions and a proportionate evaluation.',
  preparation: 'Begin with untimed practice to consolidate methods, then complete representative questions under timed and closed-resource conditions. Compare each response with the rubric and identify one improvement to reasoning, execution or interpretation.',
  workedExamples: 'Learning outcomes demonstrated: LO2 (apply an appropriate model) and LO3 (interpret results and justify a conclusion).\n\nIllustrative practice task: A city is considering a binding rent ceiling. Using an appropriate model, explain the likely short-run effects and identify one limitation of the analysis.\n\nDeveloping approach: “A rent ceiling makes rent cheaper, so demand rises and there is a shortage.” This recognises the likely direction of the result, but it does not locate the ceiling relative to equilibrium, distinguish demand from quantity demanded, analyse supply, or support the conclusion with a complete mechanism.\n\nImproved approach: “If the ceiling is set below the competitive equilibrium rent, it is binding. At that lower rent, quantity demanded increases while quantity supplied decreases, creating excess demand. A correctly labelled supply-and-demand diagram should show the shortage as the horizontal distance between those quantities. The model therefore predicts lower rent for tenants who obtain housing, but it does not show who secures a tenancy. The policy judgement must also consider rationing, search costs, housing quality and longer-run supply responses.”\n\nWhy this is stronger: it selects the model, traces each causal step, uses the diagram analytically, interprets distributional implications and qualifies the conclusion.\n\nStudent self-check: Have I identified the model and equilibrium, traced the mechanism, labelled and interpreted the diagram or calculation, stated relevant assumptions, and reached a conclusion that acknowledges what the model cannot establish?',
  commonPitfalls: 'Common pitfalls include answering a nearby question, omitting material workings, leaving diagrams unlabelled, stating a numerical result without interpretation, treating assumptions as facts and allocating time without regard to the marks available.',
  assessmentRequirements: 'Follow the approved examination instructions, answer the required number of questions, show material workings, label diagrams and use only permitted resources. Replace this fictional wording with the module’s current requirements.',
  feedbackAvailable: 'Students will receive the feedback specified by the module, supported where appropriate by a cohort-level explanation of common strengths, misconceptions and practical next steps.',
  usingFeedback: 'Compare your approach with the criteria and tiered illustration. Identify what to continue, one feature to improve and a specific practice task to complete before the next related assessment.',
  supportRoutes: 'Use the module’s published question-and-answer, office-hour or debrief arrangements. Replace this fictional wording with the confirmed support route.',
  keatsLocation: 'Module learning platform > Assessment and feedback'
};

const afterAiSample = {
  moduleCode: 'DEMO2001',
  moduleTitle: 'Applied Microeconomics (fictional example)',
  level: 'Level 5',
  faculty: 'Example Business School',
  department: 'Economics',
  moduleLeader: 'Dr Alex Morgan',
  academicYear: '2026/27',
  teachingPeriod: 'Term 1',
  assessmentProfile: 'exam',
  assessmentFormat: 'in_person_exam',
  cohortContext: 'This fictional example summarises non-identifiable cohort themes from a closed-book examination. Cohort feedback complements rather than replaces any individual feedback available to students.',
  learningOutcomes: 'LO1: Explain how incentives and constraints shape market behaviour. LO2: Apply an appropriate microeconomic model to an unfamiliar policy problem. LO3: Interpret analytical or quantitative results and reach a justified conclusion.',
  evaluatedLearning: 'The examination assessed understanding of core microeconomic concepts and the ability to select an appropriate model, use diagrams or calculations, explain economic intuition and reach a supported conclusion.',
  performancePatterns: 'Responses were generally more effective when students selected the relevant model, showed the main stages of their reasoning and connected the result explicitly to the question. No numerical performance statistics are included in this fictional example.',
  cohortStrengths: 'The cohort generally demonstrated sound knowledge of the principal concepts. Stronger responses used appropriately labelled diagrams, set out calculations clearly and explained the implications for firms, consumers or policymakers.',
  improvementAreas: 'The main opportunity is to move from describing a model to using it to answer the precise question. Responses would be stronger with clearer definitions, visible workings, explicit assumptions and fuller interpretation of the result.',
  criteriaApplication: 'The fictional rubric considered accuracy, relevance, analytical method, application, interpretation and clarity. Developing responses identified some relevant material but did not complete the reasoning. Secure responses applied an appropriate model accurately and explained the main result. Strong responses integrated method, economic intuition, assumptions, implications and proportionate evaluation.',
  improvedApproaches: 'Learning outcomes revisited: LO2 (apply an appropriate model) and LO3 (interpret results and justify a conclusion).\n\nIllustrative task: Explain the likely short-run effects of a binding rent ceiling and identify one limitation of the analysis.\n\nA limited approach stated, “Rent falls, demand rises and there is a shortage.” This was directionally relevant but did not distinguish a shift in demand from a change in quantity demanded, analyse the supply response, or explain how the conclusion followed from the model.\n\nA stronger approach would state: “When the ceiling is below equilibrium it is binding. The lower controlled rent increases quantity demanded and reduces quantity supplied, so excess demand emerges. A labelled diagram makes the size of the shortage visible. The result does not mean every tenant is better off: allocation may depend on waiting, search or informal criteria, while quality and longer-run supply may fall.”\n\nWhy this improves the answer: it corrects the terminology, completes the mechanism, uses the diagram as evidence and makes a proportionate policy judgement rather than treating the model as a complete description of reality.\n\nApply this next time: underline the command word, name the model, trace each link in the mechanism, interpret every diagram or calculation in the context of the question, then add one limitation that changes how confidently the conclusion can be used.',
  futureUse: 'Use this cohort feedback alongside any individual feedback. Identify whether your next step concerns knowledge, method selection, technical execution, interpretation or time management, then complete a focused practice task and check it against the rubric.',
  debriefSupport: 'A fictional cohort debrief and supporting materials would be signposted through the module’s usual feedback area. Replace this wording with confirmed arrangements before publication.',
  keatsLocation: 'Module learning platform > Assessment and feedback > General examination feedback'
};

const slidesAiSample = {
  ...beforeAiSample,
  learningOutcomes: 'Explain how incentives shape market behaviour. Apply an appropriate microeconomic model to an unfamiliar problem. Interpret analytical or quantitative results and reach a justified conclusion.',
  fairnessAndClarity: 'Students receive the approved rubric and an assessment briefing. Practice questions and a worked approach clarify the expected reasoning. The module team applies the published moderation process.',
  skillsEmployability: 'Critical thinking: compare plausible models and justify the most appropriate one. Quantitative reasoning: show and interpret calculations rather than report an answer alone. Communication: explain economic reasoning clearly for the intended audience. AI literacy: evaluate tool-assisted claims against theory, evidence and the assessment rules.',
  missingInformation: 'Fictional example only. Confirm the exact assessment weighting, approved learning outcome wording, permitted resources, feedback arrangements and moderation statement from current module documents.'
};

export function sampleAiResponse(stage: DocumentStage, product: 'guide' | 'slides' = 'guide') {
  if (stage === 'before' && product === 'slides') return JSON.stringify(slidesAiSample, null, 2);
  return JSON.stringify(stage === 'before' ? beforeAiSample : afterAiSample, null, 2);
}
