import { AssessmentFormat, DocumentStage, ToolkitData, formatLabels } from './types';

type ExampleBank = Partial<Record<keyof ToolkitData, string[]>>;
const commonBefore: ExampleBank = {
  expectations: ['A strong response identifies the relevant economic mechanism, applies it to the question, and explains why the evidence supports the conclusion rather than merely naming a theory.', 'Good performance combines accurate analysis with explicit assumptions, proportionate evidence and a clear line of reasoning.'],
  criteria: ['Markers will consider accuracy, analytical reasoning, appropriate use of evidence, application to the task and clarity of communication. A technically correct answer may still be limited if its assumptions or implications are not explained.'],
  preparation: ['Practise selecting an approach before looking at a solution, complete representative questions under realistic conditions, and compare your reasoning with the rubric or model approach.'],
  workedExamples: ['Use a short worked example to show how a descriptive answer can be improved by adding a mechanism, assumptions, evidence and a justified conclusion.'],
  commonPitfalls: ['Common pitfalls include answering a nearby question, reproducing material without applying it, leaving assumptions implicit, reporting output without interpretation, and allocating time or words unevenly.'],
  feedbackAvailable: ['Students will receive individual comments and/or rubric indicators, supported by a cohort-level summary explaining recurring strengths, misconceptions and practical next steps.'],
  usingFeedback: ['Translate each feedback point into one action: what to continue, what to change, and where to practise it. Revisit this plan before the next related assessment.'],
};
const commonAfter: ExampleBank = {
  cohortContext: ['This document summarises non-identifiable themes across the cohort. It complements individual feedback and does not replace comments on your own work.'],
  performancePatterns: ['Responses were generally strongest when students stated the economic mechanism before applying evidence. Do not add percentages or averages unless they have been checked and supplied by the module team.'],
  cohortStrengths: ['Many students selected relevant concepts and structured their responses clearly. Stronger work made the link between evidence and conclusion explicit.'],
  improvementAreas: ['The main opportunity is to move from description to analysis: explain the causal or strategic mechanism, state assumptions and consider the limits of the conclusion.'],
  criteriaApplication: ['Higher-performing work combined accuracy with application and judgement. The rubric was applied holistically: listing more material did not compensate for weak relevance or unexplained reasoning.'],
  improvedApproaches: ['Instead of stating that a coefficient is significant, explain its sign, magnitude, uncertainty, identifying assumptions and what the result does—and does not—support.'],
  futureUse: ['Carry this feedback into later modules by using a short pre-submission check: question answered, method justified, assumptions visible, evidence interpreted and conclusion proportionate.'],
  debriefSupport: ['Bring one paragraph, calculation or feedback point to the debrief and identify the decision you would make differently next time.'],
};
const formatBefore: Record<AssessmentFormat, ExampleBank> = {
  in_person_exam: { assessmentPurpose: ['An in-person examination is appropriate because it asks students to apply core concepts independently under time constraints, demonstrate fluency in economic or quantitative reasoning, and select and justify a method in comparable conditions. Foundational fluency also helps graduates evaluate rather than simply accept AI-generated analysis.'], preparation: ['Use timed, closed-resource practice after untimed learning. Practise identifying the method, showing essential workings and explaining the economic meaning of the result.'], assessmentRequirements: ['Answer the specified number of questions. State essential assumptions, show material workings, label diagrams and follow the published rules on permitted materials.'] },
  open_book_exam: { assessmentPurpose: ['A time-limited open-book examination assesses selection, application and judgement rather than recall alone. Access to resources makes it especially important to decide what is relevant and construct a defensible answer efficiently.'], preparation: ['Organise resources by decision or concept, not by week. Practise locating evidence quickly and answering unfamiliar questions without copying notes into the response.'] },
  essay_report: { assessmentPurpose: ['The essay or report assesses the ability to frame a focused question, integrate theory and evidence, evaluate competing explanations and communicate a reasoned conclusion for an academic or professional reader.'], expectations: ['Strong work has a clear analytical spine: each section advances the answer, evidence is evaluated rather than accumulated, and the conclusion follows from the argument.'] },
  quant_problem_set: { assessmentPurpose: ['The problem set develops quantitative fluency by requiring students to choose and execute an appropriate method, show reasoning, interpret results and diagnose whether an answer is economically plausible.'], commonPitfalls: ['Avoid presenting calculations without interpretation, rounding too early, omitting units, using a method without checking its conditions, or treating software output as self-explanatory.'] },
  econometrics_project: { assessmentPurpose: ['The data project assesses the full empirical reasoning chain: a motivated question, appropriate data and specification, reproducible analysis, interpretation, diagnostic judgement and honest discussion of limitations.'], expectations: ['Good performance explains why the design can answer the question, documents data decisions, interprets magnitude and uncertainty, and distinguishes association from causal evidence.'] },
  case_analysis: { assessmentPurpose: ['Case analysis assesses whether students can diagnose an ambiguous organisational or market problem, prioritise evidence, apply relevant frameworks selectively and recommend an implementable course of action.'], expectations: ['Strong work makes trade-offs explicit and explains why the recommended action is preferable under the case constraints.'] },
  presentation: { assessmentPurpose: ['The presentation assesses disciplined selection, audience-aware communication, evidence-based judgement and the ability to explain or defend analysis within a limited time.'], preparation: ['Rehearse aloud to time, test the narrative without slides, and prepare concise answers to likely questions about assumptions, evidence and recommendations.'] },
  group_project: { assessmentPurpose: ['The group project combines subject knowledge with coordination, integration of different contributions and collective responsibility for a coherent analytical output—capabilities used in professional economics and management work.'], commonPitfalls: ['Avoid dividing the task into disconnected pieces, leaving integration until the end, or allowing presentation consistency to substitute for analytical coherence.'] },
  take_home: { assessmentPurpose: ['A take-home task allows sustained analysis of a more complex problem. It assesses judgement in selecting methods and evidence, transparent use of permitted tools, and the ability to refine a coherent response within the stated rules.'], assessmentRequirements: ['Follow the module’s rules on collaboration, sources and AI tools. Where AI use is permitted, verify outputs, disclose use as required and remain responsible for every claim, calculation and citation.'] },
};

export function examplesFor(stage: DocumentStage, format: AssessmentFormat | ''): ExampleBank {
  const base = stage === 'before' ? commonBefore : commonAfter;
  if (stage === 'after' || !format) return base;
  const merged: ExampleBank = { ...base };
  for (const [key, values] of Object.entries(formatBefore[format])) merged[key as keyof ToolkitData] = [...(base[key as keyof ToolkitData] || []), ...(values || [])];
  return merged;
}

export function aiPrompt(stage: DocumentStage, format: AssessmentFormat | '') {
  const formatText = format ? formatLabels[format] : 'the assessment format supported by the source material';
  const shared = `You are helping a university module leader create an editable student-facing document for an undergraduate economics or management module. Use only the supplied sources. Do not invent facts, dates, rules, links, statistics or cohort results. Leave unsupported values empty. Use concise, constructive language. Do not include student names, IDs, individual scripts, raw marks, named comments or identifiable student information. Return ONLY one valid JSON object with string values and no markdown.`;
  if (stage === 'before') return `${shared}\n\nCreate an Assessment and Feedback Guide for ${formatText}. Use exactly these keys:\n${JSON.stringify({ moduleCode:'', moduleTitle:'', level:'', faculty:'', department:'', moduleLeader:'', academicYear:'', teachingPeriod:'', assessmentProfile:'', assessmentFormat:format, assessmentStructure:'', assessmentPurpose:'', expectations:'', criteria:'', preparation:'', workedExamples:'', commonPitfalls:'', assessmentRequirements:'', feedbackAvailable:'', usingFeedback:'', supportRoutes:'', keatsLocation:'' }, null, 2)}\n\nUse assessmentProfile values exam, mixed or coursework. Explain the educational purpose without claiming the format is inherently superior or valuable merely because it restricts AI. Distinguish supported information from gaps by leaving gaps empty.`;
  return `${shared}\n\nCreate a cohort-level General Feedback document for ${formatText}. Suggested inputs are the assessment brief, current rubric, learning outcomes and anonymised aggregate themes. Never infer or calculate performance statistics; include a numeric pattern only when explicitly supplied and checked. Use exactly these keys:\n${JSON.stringify({ moduleCode:'', moduleTitle:'', level:'', faculty:'', department:'', moduleLeader:'', academicYear:'', teachingPeriod:'', assessmentProfile:'', assessmentFormat:format, cohortContext:'', evaluatedLearning:'', performancePatterns:'', cohortStrengths:'', improvementAreas:'', criteriaApplication:'', improvedApproaches:'', futureUse:'', debriefSupport:'', keatsLocation:'' }, null, 2)}\n\nUse assessmentProfile values exam, mixed or coursework. Make clear that cohort feedback complements rather than replaces individual feedback. Leave unsupported values empty.`;
}
